language: node_js
node_js:
- node
sudo: false
install: yarn install
script:
- echo "skipping tests"
deploy:
  provider: heroku
  api_key:
   secure: "geFPmgUyT3I0qNE94a6OlqKayWh1BLXQ1V+WmBoT39xaxHUbRk/216YZJ7WSe/LU+eCbWkQ8c6SRlzzFdWOpdjwRzwXkU9cy34r40c3sFNpzYzmJlEaqs95+P0OVQ1d/mgRH8qavYdYVlmnbOQfB2TcURCRzLqRZf6PiJ6HGS/HZ/C2MxuC6RQgo9e6tRARy8BnQdVKQovEfsj5dNvvKD2/9gPzstDJJXnJhipMyI7eawmTwL3yTjr5Ptw4vt1aN9hXqFgapaqmLacNk0kQTtTXTrdNl13xKbng9VJKnYYnfl+ckhPVrvbAfZt1W5B01rRid4o4a/SEtyAVH0vwnHapYOym3vRgYrwooVvRoT/tQp2OfMtPGLXW7ZfPkElO7FqBZz8Dwt8Pa5bIUKOSunUCYm6enwSRxBsMbNOHdE0wY4DveUjJs8ktKW25STfox0TZ5BfHNoNIDgDho9gVq0Rl4vmZVPsjgnQApm5T89VAJxxpGiKw9fvfIGzPthWnTkKC9pG/TM5qTiVu1W3B8aGmGyFQUS0yy/X5ROcTmnKjoKqgN3DI3z54ZoCubRIZ2vR2SXg/o8wVonHMBZRwebEzvWU/YxyAwYF2Q1GS35gmPWXH+ywxW/hcC8+fIsEs2iivw66Z+qYK4RHr/zB780ECx9w5FGreR0AvV+NYn/B4="
  app: react-todo-board
  on:
    repo: alpersonalwebsite/react-todo-board